from datetime import datetime

from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Text
from sqlalchemy.orm import relationship

from backend.database import Base

# ----------------------------------------------
# Document -> Stores the uploaded legal document record.
# ----------------------------------------------

class Document(Base):
    __tablename__ = "documents"

    # Primary Key
    id = Column(Integer, primary_key=True, index=True)

    # Uploaded document file name
    file_name = Column(String, nullable=False)

    # Path where the file is saved on disk
    file_path = Column(String, nullable=True)

    # Upload timestamp
    uploaded_at = Column(DateTime, default=datetime.utcnow)

    # Document classification
    document_type = Column(String, nullable=True)

    # Current processing status
    status = Column(String, default="uploaded")

    # Final legal review summary generated by the AI
    final_summary = Column(Text, nullable=True)

    # Relationships to child tables
    clauses = relationship("Clause", back_populates="document")
    risk_flags = relationship("RiskFlag", back_populates="document")
    review_decisions = relationship("ReviewDecision", back_populates="document")

# ----------------------------------------------
# Clause -> Stores individual clauses extracted from a document.
# ----------------------------------------------

class Clause(Base):
    __tablename__ = "clauses"

    # Primary Key
    id = Column(Integer, primary_key=True, index=True)

    # Foreign key linking this clause to its parent document
    document_id = Column(Integer, ForeignKey("documents.id"), nullable=False)

    # Identifies which analysis/re-analysis run produced this clause
    analysis_run_id = Column(Integer, nullable=False)

    # Type/category of the clause
    clause_type = Column(String, nullable=True)

    # Full text content of the clause
    clause_text = Column(Text, nullable=True)

    # Relationship back to the parent document
    document = relationship("Document", back_populates="clauses")

# ----------------------------------------------
# RiskFlag -> Stores individual legal risk flags identified in a document.
# ----------------------------------------------

class RiskFlag(Base):
    __tablename__ = "risk_flags"

    # Primary Key
    id = Column(Integer, primary_key=True, index=True)

    # Foreign key linking this risk flag to its parent document
    document_id = Column(Integer, ForeignKey("documents.id"), nullable=False)

    # Identifies which analysis/re-analysis run produced this risk
    analysis_run_id = Column(Integer, nullable=False)

    # Severity level
    severity = Column(String, nullable=True)

    # Type of legal risk
    risk_type = Column(String, nullable=True)

    # The clause in the document that is affected
    affected_clause = Column(String, nullable=True)

    # Explanation of why this is a risk
    rationale = Column(Text, nullable=True)

    # Where the evidence was found in the document
    source_location = Column(String, nullable=True)

    # Recommended action for this risk
    recommended_action = Column(Text, nullable=True)

    # AI confidence score (0 to 100)
    confidence = Column(Integer, nullable=True)

    # Relationship back to the parent document
    document = relationship("Document", back_populates="risk_flags")

# ----------------------------------------------
# ReviewDecision -> Stores human review decisions made for a document.
# ----------------------------------------------

class ReviewDecision(Base):
    __tablename__ = "review_decisions"

    # Primary Key
    id = Column(Integer, primary_key=True, index=True)

    # Foreign key linking this decision to its parent document
    document_id = Column(Integer, ForeignKey("documents.id"), nullable=False)

    # Identifies which analysis/re-analysis run this decision belongs to
    analysis_run_id = Column(Integer, nullable=False)

    # The decision made by the human reviewer
    decision = Column(String, nullable=False)

    # Timestamp of when the review decision was submitted
    reviewed_at = Column(DateTime, default=datetime.utcnow)

    # Relationship back to the parent document
    document = relationship("Document", back_populates="review_decisions")